// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mholabwckmnsngejfkij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ob2xhYndja21uc25nZWpma2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTQwNDUsImV4cCI6MjA3MjIzMDA0NX0.yrR3XH04uKsb9MP_K2hwRz3P7VAMnvvs3tM_0fqSt_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});